
controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

app_categorie:
    path: '/categorie/{id}'
    controller: 'App\Controller\CategorieController::show'
